language: node_js

sudo: false

node_js:
  - 10

cache: npm


branches:
  only:
    - hexo

addons:
  ssh_known_hosts: github.com

before_script:
 - git config --global user.name "Jonkimi"
 - git config --global user.email "JonkimyLiao@gmail.com"
 - git clone https://github.com/Jonkimi/jonkimi.github.io.git public

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: public
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: hexo
  repo: jonkimi/jonkimi.github.io
  target_branch: master